import {
    Users,
    Layers,
    DollarSign,
    Headphones,
    UserCheck,
    CreditCard,
    AlertTriangle,
    CheckCircle,
    Star,
    UserPlus,
    Home,
    ShoppingCart,
    MessageSquare,
    HelpCircle,
    BarChart3,
    FileText,
} from "lucide-react";
import {
    MockUser,
    SidebarItem,
} from "@/shared/types/admin";
import {
    PlatformStat,
    RecentActivity,
    Notification,
} from "@/shared/types/admin/dashboard";
import { ActiveProject } from "@/shared/types/project";
import {
    FinancialData,
    FinancialOverview,
} from "@/shared/types/finance";
import { Order } from "@/shared/types/order";
import { Payment } from "@/shared/types/payment";
import { AnalyticsData } from "@/shared/types/admin/analytics";

// Mock users data
export const usersData: MockUser[] = [
    {
        id: 1,
        name: "Sarah Chen",
        email: "sarah.chen@example.com",
        avatar: "/placeholder.svg?height=40&width=40",
        role: "Client",
        status: "active",
        joinDate: "2024-12-15",
        lastActive: "2 hours ago",
        projects: 5,
        totalSpent: "$24,500",
        totalEarned: "$0",
        location: "San Francisco, CA",
        phone: "+1 (555) 123-4567",
        verified: true,
        rating: 4.8,
        completedProjects: 12,
    },
    {
        id: 2,
        name: "Marcus Rodriguez",
        email: "marcus@designstudio.com",
        avatar: "/placeholder.svg?height=40&width=40",
        role: "Provider",
        status: "active",
        joinDate: "2024-08-20",
        lastActive: "30 minutes ago",
        projects: 18,
        totalSpent: "$0",
        totalEarned: "$89,200",
        location: "Austin, TX",
        phone: "+1 (555) 987-6543",
        verified: true,
        rating: 4.9,
        completedProjects: 45,
    },
    {
        id: 3,
        name: "Emily Watson",
        email: "emily.watson@techcorp.com",
        avatar: "/placeholder.svg?height=40&width=40",
        role: "Client",
        status: "pending",
        joinDate: "2025-01-20",
        lastActive: "1 day ago",
        projects: 0,
        totalSpent: "$0",
        totalEarned: "$0",
        location: "New York, NY",
        phone: "+1 (555) 456-7890",
        verified: false,
        rating: 0,
        completedProjects: 0,
    },
    {
        id: 4,
        name: "David Kim",
        email: "david@creativeworks.com",
        avatar: "/placeholder.svg?height=40&width=40",
        role: "Provider",
        status: "active",
        joinDate: "2024-06-10",
        lastActive: "5 minutes ago",
        projects: 12,
        totalSpent: "$0",
        totalEarned: "$67,800",
        location: "Los Angeles, CA",
        phone: "+1 (555) 234-5678",
        verified: true,
        rating: 4.7,
        completedProjects: 28,
    },
    {
        id: 5,
        name: "Lisa Thompson",
        email: "lisa.thompson@startup.com",
        avatar: "/placeholder.svg?height=40&width=40",
        role: "Client",
        status: "suspended",
        joinDate: "2024-11-05",
        lastActive: "2 weeks ago",
        projects: 3,
        totalSpent: "$8,900",
        totalEarned: "$0",
        location: "Seattle, WA",
        phone: "+1 (555) 345-6789",
        verified: true,
        rating: 3.2,
        completedProjects: 2,
    },
    {
        id: 6,
        name: "Alex Morgan",
        email: "alex@freelancedesign.com",
        avatar: "/placeholder.svg?height=40&width=40",
        role: "Provider",
        status: "active",
        joinDate: "2024-09-15",
        lastActive: "1 hour ago",
        projects: 8,
        totalSpent: "$0",
        totalEarned: "$42,300",
        location: "Chicago, IL",
        phone: "+1 (555) 567-8901",
        verified: true,
        rating: 4.6,
        completedProjects: 19,
    },
    {
        id: 7,
        name: "Jennifer Lee",
        email: "jennifer@marketing.com",
        avatar: "/placeholder.svg?height=40&width=40",
        role: "Client",
        status: "active",
        joinDate: "2024-10-30",
        lastActive: "3 hours ago",
        projects: 7,
        totalSpent: "$18,700",
        totalEarned: "$0",
        location: "Miami, FL",
        phone: "+1 (555) 678-9012",
        verified: true,
        rating: 4.4,
        completedProjects: 8,
    },
    {
        id: 8,
        name: "Robert Wilson",
        email: "robert@webdev.com",
        avatar: "/placeholder.svg?height=40&width=40",
        role: "Provider",
        status: "pending",
        joinDate: "2025-01-18",
        lastActive: "6 hours ago",
        projects: 0,
        totalSpent: "$0",
        totalEarned: "$0",
        location: "Denver, CO",
        phone: "+1 (555) 789-0123",
        verified: false,
        rating: 0,
        completedProjects: 0,
    },
];

// Platform statistics
export const platformStats: PlatformStat[] = [
    {
        title: "Total Users",
        value: "12,847",
        change: "+12.5%",
        icon: <Users className="text-sky-500" />,
        trend: "up",
        bgColor: "bg-sky-50",
    },
    {
        title: "Active Projects",
        value: "3,421",
        change: "+8.2%",
        icon: <Layers className="text-emerald-500" />,
        trend: "up",
        bgColor: "bg-emerald-50",
    },
    {
        title: "Revenue (MTD)",
        value: "$284,592",
        change: "+15.3%",
        icon: <DollarSign className="text-violet-500" />,
        trend: "up",
        bgColor: "bg-violet-50",
    },
    {
        title: "Support Tickets",
        value: "127",
        change: "-5.1%",
        icon: <Headphones className="text-amber-500" />,
        trend: "down",
        bgColor: "bg-amber-50",
    },
];

// Recent activities
export const recentActivities: RecentActivity[] = [
    {
        id: 1,
        type: "user_registration",
        user: "Sarah Chen",
        action: "New user registered",
        time: "2 minutes ago",
        status: "success",
        icon: <UserCheck className="text-emerald-500" />,
        avatar: "/placeholder.svg?height=40&width=40",
    },
    {
        id: 2,
        type: "payment",
        user: "Project #3421",
        action: "Payment of $2,500 processed",
        time: "15 minutes ago",
        status: "success",
        icon: <CreditCard className="text-sky-500" />,
        avatar: "/placeholder.svg?height=40&width=40",
    },
    {
        id: 3,
        type: "support",
        user: "Michael Rodriguez",
        action: "Support ticket created",
        time: "1 hour ago",
        status: "pending",
        icon: <AlertTriangle className="text-amber-500" />,
        avatar: "/placeholder.svg?height=40&width=40",
    },
    {
        id: 4,
        type: "project",
        user: "Website Redesign",
        action: "Project milestone completed",
        time: "2 hours ago",
        status: "success",
        icon: <CheckCircle className="text-emerald-500" />,
        avatar: "/placeholder.svg?height=40&width=40",
    },
    {
        id: 5,
        type: "review",
        user: "Emma Thompson",
        action: "New review submitted (5 stars)",
        time: "3 hours ago",
        status: "success",
        icon: <Star className="text-amber-500" />,
        avatar: "/placeholder.svg?height=40&width=40",
    },
];

// Notifications
export const notificationsData: Notification[] = [
    {
        id: 1,
        icon: <UserPlus className="h-4 w-4 text-sky-500" />,
        text: "New user 'John Doe' has registered.",
        time: "10m ago",
    },
    {
        id: 2,
        icon: <DollarSign className="h-4 w-4 text-emerald-500" />,
        text: "Payment of $1,250 for PRJ-002 received.",
        time: "1h ago",
    },
    {
        id: 3,
        icon: <AlertTriangle className="h-4 w-4 text-rose-500" />,
        text: "System alert: Database usage at 92%.",
        time: "2h ago",
    },
    {
        id: 4,
        icon: <CheckCircle className="h-4 w-4 text-emerald-500" />,
        text: "Project 'Mobile App Design' has been completed.",
        time: "5h ago",
    },
];

// Active projects
export const activeProjects: ActiveProject[] = [
    {
        id: "PRJ-001",
        name: "E-commerce Platform",
        client: "TechCorp Inc.",
        provider: "WebDev Solutions",
        status: "in_progress",
        progress: 75,
        budget: "$45,000",
        deadline: "June 15, 2025",
        priority: "high",
    },
    {
        id: "PRJ-002",
        name: "Mobile App Design",
        client: "StartupXYZ",
        provider: "Design Studio Pro",
        status: "review",
        progress: 90,
        budget: "$28,000",
        deadline: "May 30, 2025",
        priority: "medium",
    },
    {
        id: "PRJ-003",
        name: "Brand Identity Package",
        client: "Local Restaurant",
        provider: "Creative Agency",
        status: "completed",
        progress: 100,
        budget: "$12,000",
        deadline: "April 20, 2025",
        priority: "low",
    },
    {
        id: "PRJ-004",
        name: "Video Production",
        client: "Marketing Firm",
        provider: "Video Experts",
        status: "dispute",
        progress: 60,
        budget: "$35,000",
        deadline: "July 10, 2025",
        priority: "high",
    },
];

// Financial data
export const financialData: FinancialData[] = [
    {
        period: "This Month",
        revenue: "$284,592",
        commissions: "$42,689",
        refunds: "$3,240",
        net: "$238,663",
    },
    {
        period: "Last Month",
        revenue: "$247,831",
        commissions: "$37,175",
        refunds: "$2,890",
        net: "$207,766",
    },
];

// Financial overview for dashboard
export const financialOverview: FinancialOverview = {
    totalRevenue: "$284,592",
    monthlyRevenue: "$42,689",
    transactions: "1,847",
    pendingPayouts: "$12,340",
};

// Sidebar items
export const sidebarItems: SidebarItem[] = [
    {
        title: "Dashboard",
        icon: <Home />,
        isActive: true,
        url: "#dashboard",
    },
    {
        title: "Users",
        icon: <Users />,
        badge: "1,247",
        items: [
            { title: "All Users", url: "#users", badge: "1,247" },
            { title: "Active Users", url: "#users-active", badge: "892" },
            { title: "Provider Requests", url: "#users-provider-requests", badge: "5" },
            { title: "Pending Approval", url: "#users-pending", badge: "23" },
            { title: "Suspended", url: "#users-suspended", badge: "12" },
        ],
    },
    {
        title: "Projects",
        icon: <Layers />,
        badge: "156",
        items: [
            { title: "Active Projects", url: "#projects-active", badge: "89" },
            { title: "Completed", url: "#projects-completed", badge: "67" },
            { title: "On Hold", url: "#projects-hold", badge: "12" },
            { title: "Templates", url: "#projects-templates" },
        ],
    },
    {
        title: "Orders",
        icon: <ShoppingCart />,
        badge: "45",
        items: [
            { title: "New Orders", url: "#orders-new", badge: "12" },
            { title: "In Progress", url: "#orders-progress", badge: "23" },
            { title: "Completed", url: "#orders-completed", badge: "156" },
            { title: "Refunds", url: "#orders-refunds", badge: "3" },
        ],
    },
    {
        title: "Payments",
        icon: <CreditCard />,
        items: [
            { title: "Transactions", url: "#payments-transactions" },
            { title: "Pending Payments", url: "#payments-pending", badge: "8" },
            { title: "Refunds", url: "#payments-refunds" },
            { title: "Reports", url: "#payments-reports" },
        ],
    },
    {
        title: "Communications",
        icon: <MessageSquare />,
        badge: "28",
        items: [
            { title: "Messages", url: "#communications-messages", badge: "15" },
            { title: "Video Calls", url: "#communications-video" },
            {
                title: "Notifications",
                url: "#communications-notifications",
                badge: "13",
            },
            { title: "Announcements", url: "#communications-announcements" },
        ],
    },
    {
        title: "Reviews",
        icon: <Star />,
        items: [
            { title: "All Reviews", url: "#reviews-all" },
            { title: "Pending Moderation", url: "#reviews-pending", badge: "7" },
            { title: "Reported Reviews", url: "#reviews-reported", badge: "2" },
            { title: "Analytics", url: "#reviews-analytics" },
        ],
    },
    {
        title: "Support",
        icon: <HelpCircle />,
        badge: "12",
        items: [
            { title: "Open Tickets", url: "#support-open", badge: "12" },
            { title: "Resolved", url: "#support-resolved" },
            { title: "Knowledge Base", url: "#support-knowledge" },
            { title: "FAQ Management", url: "#support-faq" },
        ],
    },
    {
        title: "Analytics",
        icon: <BarChart3 />,
        items: [
            { title: "Platform Overview", url: "#analytics-overview" },
            { title: "User Analytics", url: "#analytics-users" },
            { title: "Revenue Reports", url: "#analytics-revenue" },
            { title: "Performance Metrics", url: "#analytics-performance" },
        ],
    },
    {
        title: "Content",
        icon: <FileText />,
        items: [
            { title: "Pages Management", url: "#content-pages" },
            { title: "Media Library", url: "#content-media" },
            { title: "SEO Settings", url: "#content-seo" },
            { title: "Blog Posts", url: "#content-blog" },
        ],
    },
];

// Orders data
export const ordersData: Order[] = [
    {
        id: "ORD-001",
        client: "Sarah Chen",
        service: "Website Development",
        amount: "$4,500",
        status: "completed",
        date: "2025-01-15",
        priority: "high",
    },
    {
        id: "ORD-002",
        client: "Michael Rodriguez",
        service: "Mobile App Design",
        amount: "$3,200",
        status: "in-progress",
        date: "2025-01-14",
        priority: "medium",
    },
    {
        id: "ORD-003",
        client: "Emma Thompson",
        service: "Logo Design",
        amount: "$800",
        status: "pending",
        date: "2025-01-14",
        priority: "low",
    },
    {
        id: "ORD-004",
        client: "David Kim",
        service: "E-commerce Development",
        amount: "$7,500",
        status: "in-progress",
        date: "2025-01-13",
        priority: "high",
    },
    {
        id: "ORD-005",
        client: "Olivia Chen",
        service: "Content Writing",
        amount: "$1,200",
        status: "completed",
        date: "2025-01-12",
        priority: "medium",
    },
];

// Payments data
export const paymentsData: Payment[] = [
    {
        id: "PAY-001",
        client: "Sarah Chen",
        amount: "$4,500",
        status: "completed",
        date: "2025-01-15",
        method: "Credit Card",
    },
    {
        id: "PAY-002",
        client: "Michael Rodriguez",
        amount: "$3,200",
        status: "pending",
        date: "2025-01-14",
        method: "PayPal",
    },
    {
        id: "PAY-003",
        client: "Emma Thompson",
        amount: "$800",
        status: "failed",
        date: "2025-01-14",
        method: "Bank Transfer",
    },
    {
        id: "PAY-004",
        client: "David Kim",
        amount: "$7,500",
        status: "completed",
        date: "2025-01-13",
        method: "Credit Card",
    },
    {
        id: "PAY-005",
        client: "Olivia Chen",
        amount: "$1,200",
        status: "refunded",
        date: "2025-01-12",
        method: "PayPal",
    },
];

// Analytics data
export const analyticsData: AnalyticsData = {
    users: {
        total: 12847,
        growth: 12.5,
        active: 8920,
        new: 234,
    },
    revenue: {
        total: 284592,
        growth: 15.3,
        average: 2450,
        projected: 312000,
    },
    projects: {
        total: 3421,
        growth: 8.2,
        completed: 1567,
        active: 892,
    },
    engagement: {
        rate: 68.4,
        growth: 4.2,
        duration: "12m 34s",
        pages: 4.8,
    },
};

// Support tickets initial data
export const supportTicketsData = [
    {
        id: 1,
        subject: "Login issues",
        status: "open",
        priority: "high",
        user: "John Doe",
        date: "2025-01-15",
    },
    {
        id: 2,
        subject: "Payment not processed",
        status: "in-progress",
        priority: "medium",
        user: "Sarah Chen",
        date: "2025-01-14",
    },
    {
        id: 3,
        subject: "Project delivery delay",
        status: "resolved",
        priority: "low",
        user: "Michael Rodriguez",
        date: "2025-01-13",
    },
];
