export enum UserRole {
    USER = "USER",
    ADMIN = "ADMIN",
    SUPER_ADMIN = "SUPER_ADMIN",
    PROVIDER = "PROVIDER",
    PENDING_PROVIDER = "PENDING_PROVIDER",
    REJECTED_PROVIDER = "REJECTED_PROVIDER",
    EMPLOYEE = "EMPLOYEE",
}

export enum AdminPrivilege {
    OPERATIONS = "OPERATIONS",
    USERS = "USERS",
    PROFILES = "PROFILES",
    SERVICES = "SERVICES",
    PAYMENTS = "PAYMENTS",
    SUBSCRIPTIONS = "SUBSCRIPTIONS",
    SETTINGS = "SETTINGS",
    REPORTS = "REPORTS",
}
