export enum UserRole {
    // Module 1: Primary Roles
    CLIENT = "CLIENT",
    PROVIDER_PENDING = "PROVIDER_PENDING",
    PROVIDER_APPROVED = "PROVIDER_APPROVED",
    PROVIDER_REJECTED = "PROVIDER_REJECTED",
    PROVIDER_SUSPENDED = "PROVIDER_SUSPENDED",
    ADMIN = "ADMIN",
    SUPER_ADMIN = "SUPER_ADMIN",
    // Frontend compatibility aliases (frontend uses these names)
    PENDING_PROVIDER = "PENDING_PROVIDER",
    REJECTED_PROVIDER = "REJECTED_PROVIDER",
}

export enum AdminPrivilege {
    OPERATIONS = "OPERATIONS",
    USERS = "USERS",
    PROFILES = "PROFILES",
    SERVICES = "SERVICES",
    PAYMENTS = "PAYMENTS",
    SUBSCRIPTIONS = "SUBSCRIPTIONS",
    SETTINGS = "SETTINGS",
    REPORTS = "REPORTS",
}
