Projects:
  post:
    tags:
      - Project
    summary: Create project from proposal
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - proposalId
              - providerProfileId
              - totalPrice
            properties:
              proposalId:
                type: string
              providerProfileId:
                type: string
              totalPrice:
                type: number
    responses:
      201:
        description: Project created

ProjectsMe:
  get:
    tags:
      - Project
    summary: Get my projects
    security:
      - bearerAuth: []
    responses:
      200:
        description: List of projects

ProjectsId:
  get:
    tags:
      - Project
    summary: Get project by ID
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      200:
        description: Project details

ProjectsIdComplete:
  patch:
    tags:
      - Project
    summary: Mark project as complete (Provider)
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      200:
        description: Project marked complete

ProjectsIdConfirm:
  patch:
    tags:
      - Project
    summary: Confirm completion (Client)
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      200:
        description: Completion confirmed

ProjectsIdCancel:
  patch:
    tags:
      - Project
    summary: Cancel project (Client)
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      200:
        description: Project cancelled

ProjectsFiles:
  get:
    tags:
      - Project
    summary: Get project files
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      200:
        description: List of files
  post:
    tags:
      - Project
    summary: Upload project file
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    requestBody:
      content:
        multipart/form-data:
          schema:
            type: object
            required:
              - file
            properties:
              file:
                type: string
                format: binary
              description:
                type: string
    responses:
      201:
        description: File upload

ProjectsFilesDelete:
  delete:
    tags:
      - Project
    summary: Delete project file
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: path
        name: fileId
        required: true
        schema:
          type: string
    responses:
      200:
        description: File deleted

ProjectsActivities:
  get:
    tags:
      - Project
    summary: Get project activities
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    responses:
      200:
        description: List of activities
