export const proficiencyLevels = [
  { value: "BASIC", label: "Basic" },
  { value: "CONVERSATIONAL", label: "Conversational" },
  { value: "FLUENT", label: "Fluent" },
  { value: "NATIVE", label: "Native or Bilingual" },
];

export const commonLanguages = [
  "English",
  "Spanish",
  "Chinese",
  "Arabic",
  "French",
  "German",
  "Portuguese",
  "Russian",
  "Hindi",
  "Japanese",
  "Italian",
  "Korean",
  "Turkish",
  "Dutch",
  "Polish",
  "Swedish",
  "Norwegian",
  "Danish",
  "Greek",
  "Hebrew",
  "Indonesian",
  "Malay",
  "Thai",
  "Vietnamese",
  "Filipino (Tagalog)",
  "Tamil",
  "Urdu",
  "Bengali",
  "Persian (Farsi)",
  "Nepali",
  "Swahili",
  "Amharic",
  "Somali",
  "Afrikaans",
  "Hausa",
  "Yoruba",
  "Igbo",
  "Quechua",
  "Guarani",
  "Creole (Haitian)",
  "Mayan Languages",
  "Czech",
  "Hungarian",
  "Romanian",
  "Ukrainian",
  "Serbian",
  "Croatian",
  "Finnish",
  "Icelandic",
];
